"""Constants for the Fröling RS232 integration."""

from __future__ import annotations

from typing import Final

DOMAIN: Final = "froeling_rs232"
PLATFORMS: Final = ["sensor"]

SENSOR_DEFINITIONS: Final = [
    {
        "key": "boiler_temperature",
        "name": "Boiler temperature",
        "address": 0,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "flue_temperature",
        "name": "Flue temperature",
        "address": 1,
        "divisor": 1,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "board_temperature",
        "name": "Board temperature",
        "address": 2,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "residual_oxygen",
        "name": "Residual oxygen",
        "address": 3,
        "divisor": 10,
        "unit": "%",
    },
    {
        "key": "primary_air_position",
        "name": "Primary air position",
        "address": 4,
        "divisor": 1,
        "unit": "%",
    },
    {
        "key": "secondary_air_position",
        "name": "Secondary air position",
        "address": 5,
        "divisor": 1,
        "unit": "%",
    },
    {
        "key": "induced_draft_speed",
        "name": "Induced draft speed",
        "address": 6,
        "divisor": 1,
        "unit": "rpm",
    },
    {
        "key": "sensor_1_temperature",
        "name": "Sensor 1 temperature",
        "address": 7,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "return_temperature",
        "name": "Return temperature",
        "address": 9,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "inlet_air_temperature",
        "name": "Inlet air temperature",
        "address": 18,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "pellet_level",
        "name": "Pellet level",
        "address": 21,
        "divisor": 207,
        "unit": "%",
    },
    {
        "key": "calculated_boiler_setpoint",
        "name": "Calculated boiler setpoint",
        "address": 27,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "stb_sleeve_temperature",
        "name": "STB sleeve temperature",
        "address": 173,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "boiler_sensor_2_temperature",
        "name": "Boiler sensor 2 temperature",
        "address": 174,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "outdoor_temperature",
        "name": "Outdoor temperature",
        "address": 1000,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
        "signed": True,
    },
    {
        "key": "heating_circuit_1_flow_temperature",
        "name": "Heating circuit 1 flow temperature",
        "address": 1030,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "heating_circuit_1_target_temperature",
        "name": "Heating circuit 1 target temperature",
        "address": 1031,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
    {
        "key": "heating_circuit_1_room_temperature",
        "name": "Heating circuit 1 room temperature",
        "address": 1032,
        "divisor": 2,
        "unit": "°C",
        "device_class": "temperature",
    },
]
